// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOcHSAjUfWV9LbwsGV2pH8NietiGkCV-w',
    appId: '1:754997803054:web:bad829bafdd3683df747bf',
    messagingSenderId: '754997803054',
    projectId: 'chatapp-6b8a8',
    authDomain: 'chatapp-6b8a8.firebaseapp.com',
    storageBucket: 'chatapp-6b8a8.appspot.com',
    measurementId: 'G-TP4X98HB6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbquUx-f9i-jNwHiU2njuSnzDZwlw6JhY',
    appId: '1:754997803054:android:e2534bca35fb77d7f747bf',
    messagingSenderId: '754997803054',
    projectId: 'chatapp-6b8a8',
    storageBucket: 'chatapp-6b8a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1n6shVs8vDS-bQiBrFpE8mfZ7WuWifA',
    appId: '1:754997803054:ios:8d5bde46e578ed03f747bf',
    messagingSenderId: '754997803054',
    projectId: 'chatapp-6b8a8',
    storageBucket: 'chatapp-6b8a8.appspot.com',
    iosClientId: '754997803054-om1itu3ofg2hlckhvbbhjrk958610cfa.apps.googleusercontent.com',
    iosBundleId: 'com.emadomarah.firebase.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1n6shVs8vDS-bQiBrFpE8mfZ7WuWifA',
    appId: '1:754997803054:ios:8d5bde46e578ed03f747bf',
    messagingSenderId: '754997803054',
    projectId: 'chatapp-6b8a8',
    storageBucket: 'chatapp-6b8a8.appspot.com',
    iosClientId: '754997803054-om1itu3ofg2hlckhvbbhjrk958610cfa.apps.googleusercontent.com',
    iosBundleId: 'com.emadomarah.firebase.chatApp',
  );
}
